name: PR Summary

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - ".gitea/workflows/*"

jobs:
  summarize_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed files
      run: |
        git fetch origin main
        git diff --name-only origin/main...HEAD > changed_files.txt

    - name: Get diff for changed files
      run: |
        git fetch origin main
        git diff origin/main...HEAD > diff.txt
